language: ruby
cache: bundler
rvm: 2.3.1

before_install:
- cp _config.yml _config.yml.backup
#- cat _medium.yml >> _config.yml

install:
- bundle install

script:
- bundle exec jekyll build

after_success:
- mv _config.yml.backup _config.yml

cache:
  directories:
    - .jekyll-crosspost_to_medium

env:
  global:
  - secure: D32UaJoGCljP1FtorzylJrlDrYyaRZcgzZTGUf1wQHscwCT2tqzIO+l6GCJPCGAbcjMcg0dC/xcBl+EBZ8YyWQzH7nSBZ/ffCIYjK16cTSvWLM01WvIzbMRQqF1RXVoY4jfYiWQGYEMxKsKlPlWn6kFStSWC1r4bE86C0VuOPflrVMofgfbWZixy4qQhX+2GValJH5PwHYeq9xSg2AEI+vGCshlNMgETHZT2OpDbG0RwwP1HL15EpKvtX0CjIqYBqjwQcMRzBlcyT8gTVJ3Vz87apUSSPUFZ8KICn8h31xEf1TgILsaMv+5p0CZoqAGdoRqpfCx+ek1F1d+RbHYl5/dPgBs9VGuRi9XOUmIUfa51cTgmMhhFjxg2GPmBYh38qYB+aZvZmJPuPlEh5FTfgW1iDQwaErP7Vp4h2dX6VgWtzJLwUsC9Z/0whXW80m14gyWIDevkX8O7sTeHoVHAht8gKvogcpPbTrxjztmzn3VVHZfq/NTXJ3Z2MGG/F6N8JpRCqpVt1+tj2VI2ruEFRaHy5FehB3+OT0OT8Wps4GZddXYthwxM2TPo83yOJdvd8wGyRH5sU72WDM3nI/Xe6jrgJZHZMB4cx/0QTDZ5dGr1UOuJfmfxmaJb924oy6enw6ndMcGd+kCYSmFC0aowpA9gaEVabY0gS+iXxH+oifo=
  - secure: kpg6g8aCZz/JAeD4KZIuvDfDR68Xq5C4woFGMp3JA2VulRUPhIOMe88fCbCflzLQtlHgM2iRqVR2duc9Kb/sQp4RoghbL5KiwIDNbsQ2l/ZE2ASCpcmDiAruTHKZJBVzD6FaA2fbphy0+9UpJkq38a9wrR6avMG6pUPbveY9pySaN3qvzDe0QkxHUpJtadwxTAm51O0D/TPtxR2/HhwhCw85m7PD7uK5rURiICXQC/PG0pwovOBKpdf2+fyXllh1gk7t+aUUsXKvmpNTuQLJqhkxDYst9w1PdvpG6aZpFSGV7gkjJAW2xUnYIJLz14v8ON/LG1lNKqLihXkosfF5PFuTO5wsSUJYmGvdi1w1YIt7f3PVo9MmpYWMDBWv6BYyRC79E0imYgKKx1Vzw6xy/GNKFcijzbo64Jaa/jHJBtzeG8gMXAUUoMZwR3ex2+5DjDnEGonsHkmfikUjcFK/rOSouFzqG7zdZyY1gV2xiP3XiHXqbdm7CwG9qtbysWp5JPPlQ/rkyr72OwPGx69VhX0AedKFloSgZjlure7MYWeWjWIyGo7nU+PCLuAfG4QjxbJhC888iXIT9XNOwULL6sIicwGEcJtt3iKyawPR5VsUVzX1Wlql2mDmsNDOZ0Zh3dK4R3xycZ0ptHZ6EHe9HSGJuOdIZ614Z1h4kr1ktRE=
