title: walter.bio
email: contact@walter.bio
author:
  name: Walter Vargas
  twitter: walterbio
twitter:
  username: walterbio
url: "http://walter.bio"
description: |
  Sharing my experiences in the form of gists, commands, posts, and pictures of
  a set of topics including and not limited to DevOps, AWS, Cloud, Docker,
  Ansible, Programming, Jenkins, Bitcoin, Politics, Technology, Philosophy.

owner: Walter Vargas
baseurl: ""

social:
  twitter: https://twitter.com/walterbio
  instagram: https://www.instagram.com/waltervargas/

disqus:
  shortname: walterbio

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-crosspost-to-medium

exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-100878334-1
